### PR TITLE
Fix swagger UI

### PR DESCRIPTION
**Pull request by lvarin**

### CODE REVIEW

**Review by dBucik — CHANGES_REQUESTED** [review]
Does it work for you? For me, it simply does not. I had to make additional changes in local code to make it work.

Anyway, some points to the tutorial for migrating to the new version of Springfox. It mentions `Remove any @EnableSwagger2... annotations`. I do not see any changes related to this, while the annotation is used in `uk.ac.ebi.tsc.tesk.config.swagger.SwaggerConfigAuth` and `uk.ac.ebi.tsc.tesk.config.swaggerSwaggerConfigNoAuth` classes.

Also, I cannot find any change adding missing `@EnableWebMvc` annotation (from migration guide `If you are using WebMvc but you don't use the @EnableWebMvc annotation yet, add this annotation.`)

I can push my changes into a separate branch so you can test it out.

**Comment by lvarin** [comment]
Ok, please push your changes

**Comment by dBucik** [comment]
As I am not allowed to push directly into this repo, I have created a new PR - please see [#52](https://github.com/elixir-cloud-aai/tesk-api/pull/52)

**Comment by lvarin** [comment]
I double checked. It works for me:

https://csc-tesk-noauth2.rahtiapp.fi/swagger-ui/index.html

What exactly does not work for you? Is it the building process or Swagger's UI?

**Comment by martin-kuba** [comment]
[SpringFox ](https://github.com/springfox/springfox) is not maintained, I recommend moving to SpringDoc OpenAPI, see https://springdoc.org/#migrating-from-springfox

**Comment by lvarin** [comment]
Upgrading to springdoc requires redoing the Oauth implementation/configuration.

I have work on this for a couple of days and the amount of changes needed is too much for me. I have no knowledge or time to do this.

> [SpringFox ](https://github.com/springfox/springfox) is not maintained, I recommend moving to SpringDoc OpenAPI, see https://springdoc.org/#migrating-from-springfox

Indeed there are no changes since 3 years ago. So leaving this project as it is now is not an option.

**Comment by lvarin** [comment]
Just to add to the pile of problems:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project tesk: Compilation failure
[ERROR] /home/galvaro/src/tesk-api/src/main/java/uk/ac/ebi/tsc/tesk/config/swagger/SwaggerConfigAuth.java:[8,33] cannot access org.springdoc.core.models.GroupedOpenApi
[ERROR]   bad class file: /home/galvaro/.m2/repository/org/springdoc/springdoc-openapi-starter-common/2.2.0/springdoc-openapi-starter-common-2.2.0.jar(org/springdoc/core/models/GroupedOpenApi.class)
[ERROR]     class file has wrong version 61.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

springdoc only works with Java 17 or newer. Tesk-api is written for Java v1.8

**Comment by lvarin** [comment]
From what we talked F2F, we should add a 3rd person to test this PR using the deprecated framework, merge it if successful and then put the effort on a python3 migration

**Comment by trispera** [comment]
I just tested this PR.
Everything worked fine for me

We can merge

**Review by trispera — APPROVED** [review]

**Pull request merged**
